# Только чувствительные/переменные данные
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/business-db
    username: root
    password: 1234
  
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB

# External service URLs (могут меняться в разных окружениях)
allocation.url: "http://ACCOUNTING-SERVICE/api/v1/accounting/allocation"
availability.url: "http://RESOURCES-SERVICE/api/v1/resources/check"
budget.allocation.request.type: "business-trip"
